import type { Metadata } from 'next'
// import { ThemeProvider } from 'providers/theme-provider'
import { ThemeProvider } from 'next-themes'
import { Geist, Geist_Mono } from 'next/font/google'

import { Footer } from './footer'
import './globals.css'
import { Header } from './header'

// fonts
const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

// metadata
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

// layout
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<ThemeProvider attribute='class' disableTransitionOnChange themes={['dark', 'light']} defaultTheme='system'>
					<Header />
					{children}
					<Footer />
				</ThemeProvider>
			</body>
		</html>
	)
}
